/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xinws_ndkjnidemo_ndk_NdkUtils */

#ifndef _Included_com_xinws_ndkjnidemo_ndk_NdkUtils
#define _Included_com_xinws_ndkjnidemo_ndk_NdkUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xinws_ndkjnidemo_ndk_NdkUtils
 * Method:    getStringFormC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xinws_ndkjnidemo_ndk_NdkUtils_getStringFormC
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
